asterinas/vostd

Makefile, vstd_extra/src/array_ptr.rs
Broadcast group changes in Verus, https://github.com/verus-lang/verus/pull/1542
=> Update broadcast group name

xtask/src/main.rs
This PR changes the verus repo from verus-lang/verus to our own fork asterinas/verus, the build process is also improved.
=> Change verus dependncy

xtask/src/main.rs
This PR adds the `cargo xtask update` feature, it will automatically pull the latest `asterinas\verus`.
=> Add cargo xtask update

lock-protocol/src/test/rw_version/spec/common.rs, lock-protocol/src/test/rw_version/spec/tree.rs, vstd_extra/src/lib.rs, vstd_extra/src/map_extra.rs, vstd_extra/src/prelude.rs, vstd_extra/src/set_extra.rs
Fix the `Set<CursorState>` issue.
=> Fix rw_version model

lock-protocol/src/exec/mod.rs
This reverts commit 79065d57e22578af7032a7f8a7d94ff192494063.
=> Revert "Fix a flaky proof"

lock-protocol/src/spec/common.rs, lock-protocol/src/spec/tree.rs, lock-protocol/src/spec/utils.rs, vstd_extra/src/seq_extra.rs
Replace `forall_seq_values` with `Seq::all`.
=> Using the updated definitions from vstd

lock-protocol/src/exec/test_map.rs
=> Fix warnings in test_map

lock-protocol/src/exec/rw/common.rs, lock-protocol/src/exec/rw/cursor.rs, lock-protocol/src/spec/utils.rs
Prove the
```
lemma_va_level_to_nid_inc 
lemma_is_child_level_relation 
lemma_va_range_get_guard_level 
lemma_va_range_get_tree_path
```
=> Prove `admit()` related to va level

lock-protocol/src/mm/page_table/cursor/mod.rs
=> Remove wrong assumption of pte_addr and alloc_index

fvt11-pt-cursor-guards/src/page_table/cursor/mod.rs, fvt11-pt-cursor-guards/src/page_table/cursor/model.rs, fvt11-pt-cursor-guards/src/page_table/table/model.rs, vstd_extra/src/ghost_tree.rs
Thanks for sharing this interesting project.
In this PR, I update the following things:
- vstd_extra/ghost_tree.rs
+ there are several incorrect lemmas (about trace), I fix them
+ the def of `trace` seems incorrect, I modify it
+ add other lemmas
- fvt11
+ update the proof due to the change of vstd_extra
=> fix some lemmas in ghost_tree, update fvt11

vstd_extra/src/extra_num.rs
Update lemmas about `ilog2` and `is_power_2` in `vstd_extra`, it should lay the foundation for formally verifying `PagingConstsTrait`.
=> Update lemmas about `ilog2`

lock-protocol/src/exec/mod.rs, lock-protocol/src/exec/test_map.rs, lock-protocol/src/mm/frame/mod.rs, lock-protocol/src/mm/mod.rs, lock-protocol/src/mm/page_table/cursor/mod.rs, lock-protocol/src/mm/page_table/mod.rs, lock-protocol/src/mm/page_table/node/entry.rs, lock-protocol/src/mm/page_table/node/mod.rs, lock-protocol/src/mm/vm_space.rs, lock-protocol/src/x86_64/kspace.rs, vstd_extra/src/extra_num.rs
- Add `lemma_consts_properties` in `PagingConstsTrait`
- Prove `lemma_consts_properties` for `PaginGConsts`
- Use the correct definition of `page_size`, `nr_subpage_per_huge`.
@zouyonghao Please let me know if there are any conflicts.
=> Verify `PagingConstsTrait`

lock-protocol/src/mm/page_table/cursor/mod.rs
=> Enable take_next verification

lock-protocol/src/mm/page_table/cursor/mod.rs
=> More complete path_wf

lock-protocol/src/exec/mod.rs
=> Prove create_new_frame

lock-protocol/src/mm/page_table/node/mod.rs, lock-protocol/src/spec/sub_pt/mod.rs
=> Prove write_pte

lock-protocol/src/exec/test_map.rs, lock-protocol/src/mm/page_table/cursor/mod.rs, lock-protocol/src/mm/page_table/node/entry.rs, lock-protocol/src/mm/page_table/node/mod.rs, lock-protocol/src/spec/sub_pt/mod.rs, lock-protocol/src/spec/sub_pt/state_machine.rs
=> Prove replace_with_none wf

lock-protocol/src/mm/page_table/cursor/mod.rs, lock-protocol/src/mm/page_table/node/entry.rs, xtask/src/main.rs
=> Map path_wf

lock-protocol/src/mm/page_table/cursor/spec_helpers.rs
=> Minor: remove inline for spt_do_not_change_except

lock-protocol/src/spec/rcu/tree.rs, lock-protocol/src/spec/utils.rs
Prove for 
```
initialize_inductive
protocol_lock_start_inductive
protocol_lock_inductive
protocol_lock_skip_inductive
protocol_lock_end_inductive
protocol_unlock_start_inductive
protocol_unlock_inductive
protocol_unlock_skip_inductive
protocol_unlock_end_inductive
normal_lock_inductive
normal_unlock_inductive
```
=> Proof for RCU tree spec

lock-protocol/src/spec/rcu/tree.rs
=> Add triggers

lock-protocol/src/spec/rcu/tree.rs
=> Simplify rcu inv defintion

lock-protocol/src/helpers/align_ext.rs, lock-protocol/src/mm/page_table/mod.rs
Prove lemma_aligned_pte_index_unchanged.
=> Prove lemma_aligned_pte_index_unchanged

lock-protocol/src/mm/page_table/cursor/mod.rs
=> Trival TODOs

lock-protocol/src/exec/mod.rs, lock-protocol/src/exec/test_map.rs, lock-protocol/src/lib.rs, lock-protocol/src/mm/frame/allocator.rs, lock-protocol/src/mm/page_table/cursor/mod.rs, lock-protocol/src/mm/page_table/node/mod.rs
=> Make cursor runnable again

lock-protocol/src/mm/frame/frame_ref.rs, lock-protocol/src/mm/page_table/mod.rs, lock-protocol/src/mm/page_table/node/child.rs, lock-protocol/src/mm/page_table/node/entry.rs
=> Refine specifications for FrameRef and Entry for child, entry and spt relation

lock-protocol/src/mm/page_table/node/child.rs, lock-protocol/src/mm/page_table/node/entry.rs
=> Prove the is_last case in to_ref

lock-protocol/src/mm/page_table/cursor/mod.rs, lock-protocol/src/mm/page_table/cursor/spec_helpers.rs, lock-protocol/src/mm/page_table/node/entry.rs, lock-protocol/src/mm/page_table/node/mod.rs, lock-protocol/src/spec/sub_pt/state_machine.rs
Please check spt_do_not_change_except_modify_pte @junyang-zh
=> Fix spt_do_not_change
